CREATE TABLE IF NOT EXISTS ATVsummary (

  `timestamp` datetime NOT NULL,
  `origin` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `arch` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `productmodel` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_script` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `55vmapper` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `42vmapper` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pogo` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vmapper` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pogo_update` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vm_update` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `temperature` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `magisk` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `magisk_modules` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MACw` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MACe` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ext_ip` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diskSysPct` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diskDataPct` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `numPogo` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bootdelay` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gzip` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `betamode` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `selinux` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `daemon` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authpassword` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authuser` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authid` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postdest` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fridastarted` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `patchedpid` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `openlucky` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rebootminutes` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deviceid` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `websocketurl` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `catchPokemon` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `catchRare` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `launcherver` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rawpostdest` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lat` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lon` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `overlay` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
	
  PRIMARY KEY (`origin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;